apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: iib
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iib
    app.kubernetes.io/part-of: iib
  name: iib
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: iib
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: iib
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ynanavat-tenant/iib/iib@sha256:a50b33e3874983caf397eac3d9d71c4a44529ea1ca8ad3edc80f6bda2f1bbdee
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
