apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: iib
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iib
    app.kubernetes.io/part-of: iib
  name: iib
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: iib
status:
  loadBalancer: {}
