apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: iib-worker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iib-worker
    app.kubernetes.io/part-of: iib
  name: iib-worker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: iib-worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: iib-worker
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ynanavat-tenant/iib/iib-worker@sha256:e30893b7d510a19ada165297a02dc41ceaff7c7a1a1929e7d70200170c6d2c3b
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
